// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwmwwsthduvmuyhynwol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bXd3c3RoZHV2bXV5aHlud29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTI2NTgsImV4cCI6MjA2Nzc2ODY1OH0.Sc8P_DeNMro27ZHGUyr8Pahlpz0_MVPFqGCyn_GRLZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});